### ISSUE TITLE
upload openapi.json only on failures

### ISSUE THREAD

**Issue by ckunki** [exasol/saas-api-python#61]
See https://github.com/actions/upload-artifact

Uploading multiple files: 
```yaml
      - name: Upload openapi.json
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: openapi.json
```
